chore: add ramda
mccraveiro/cheddar pull request #12
Opened 2019-10-18 18:16 UTC by 0liveira

### Contexto
Percebi que esse repositório não tinha ramda.

### Solução
Adicionei o ramda.

2019-10-18 19:39 UTC, flyingluscas commented
Ótimo trabalho!

2019-10-18 19:40 UTC, flyingluscas approved these changes

2019-10-18 19:41 UTC, nikolasrangel requested changes

2019-10-18 19:41 UTC, nikolasrangel commented on package.json
> +    "ramda": "^0.26.1"
```suggestion
    "ramda": "0.26.1"
```

2019-10-18 19:42 UTC, eduardogspereira commented
![tenor](https://user-images.githubusercontent.com/13531067/67123279-3a925d00-f1c6-11e9-9ea2-9c2231b02ca1.gif)

2019-10-18 20:13 UTC, flyingluscas approved these changes

2019-10-18 20:20 UTC, nikolasrangel approved these changes

2021-01-29 20:20 UTC, flyingluscas approved these changes

2021-01-29 22:49 UTC, otaviopace approved these changes

2021-02-01 21:10 UTC, flyingluscas approved these changes

2021-02-01 21:11 UTC, flyingluscas approved these changes

2021-02-02 17:12 UTC, otaviopace approved these changes

2021-02-02 20:45 UTC, flyingluscas approved these changes

2021-02-02 20:52 UTC, otaviopace approved these changes

2021-02-03 01:51 UTC, uselessdev approved these changes

2021-02-03 01:55 UTC, closed without merging

2021-02-03 01:58 UTC, flyingluscas commented
😠